baseURL = "https://mhu.dev/"
languageCode = "en-us"
title = "DevOoops"
theme = "ananke"

[params]
  favicon = "/img/mh256.png"
  description = "Online presence of Manuel Hutter"
  facebook = ""
  twitter = "https://twitter.com/dratir"
  instagram = ""
  youtube = ""
  github = "https://github.com/mhutter"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = "https://stackoverflow.com/users/405454/mhutter"
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-gray"
  recent_posts_number = 20
