baseURL = "https://mhu.dev/"
languageCode = "en"
title = "mhutter"
theme = "mhu"
enableRobotsTXT = true

[markup]
  [markup.highlight]
    style = "solarized-dark256"
    tabWidth = 2

[params]
  subtitle = "DevOoops"
  favicon = "/img/mh256.png"
  logo = "/img/mh256.png"
  description = "Online presence of Manuel Hutter"
  github = "https://github.com/mhutter"
  stackoverflow = "https://stackoverflow.com/users/405454/mhutter"
  recent_posts_number = 20
