baseURL = "https://mhu.dev/"
languageCode = "en"
title = "DevOoops"
theme = "mhu"

[markup]
  [markup.highlight]
    style = "dracula"
    tabWidth = 2

[params]
  favicon = "/img/mh256.png"
  description = "Online presence of Manuel Hutter"
  twitter = "https://twitter.com/dratir"
  github = "https://github.com/mhutter"
  stackoverflow = "https://stackoverflow.com/users/405454/mhutter"
  recent_posts_number = 20
