---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mhu-blog
commonLabels:
  app: blog
resources:
  - blog.deployment.yaml
  - blog.svc.yaml
  - blog.route.yaml
  - deployer.sa.yaml
