---
name: Build and test

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: srt32/hugo-action@master
      - uses: chabad360/htmlproofer@master
        with:
          directory: ./public
          arguments: --check-sri=true --http-status-ignore=999
